"""Every port in the system.

Ports live here rather than beside their implementations: a protocol next to its only
implementation is not a boundary, it is decoration (docs/03 §2).

Ports are structural `typing.Protocol`s, speak only in immutable value objects, depend on
nothing but the standard library, and declare the errors they may raise. The full catalogue
is documented in docs/03 §5; protocols are added here as the milestones that need them land.
"""

from __future__ import annotations

from hedwig.core.ports.brain import (
    ContextItem,
    Guard,
    Intent,
    MindReader,
    Plan,
    Planner,
    RecalledContext,
    Recaller,
    Responder,
    ResponseContext,
    SafetyVerdict,
    ToolOutcome,
    ToolRequest,
    ToolRunner,
    TrustTier,
    TurnAnnouncer,
    TurnPolicy,
    TurnSummary,
)
from hedwig.core.ports.clock import Clock
from hedwig.core.ports.config import (
    ConfigChange,
    ConfigEntry,
    ConfigListener,
    ConfigManager,
    ConfigSource,
)
from hedwig.core.ports.emotion import (
    DIMENSIONS,
    NEUTRAL,
    Appraisal,
    AppraisalDimension,
    BehaviourParameters,
    Dimension,
    EmotionReader,
    EmotionSnapshot,
    EmotionState,
)
from hedwig.core.ports.event_bus import (
    Delivery,
    Event,
    EventBus,
    EventHandler,
    Subscription,
)
from hedwig.core.ports.llm import (
    FinishReason,
    GenerationRequest,
    GenerationResult,
    LLMProvider,
    Message,
    ModelInfo,
    ModelTier,
    ProviderHealth,
    RequestPriority,
    Role,
    StreamChunk,
    TokenUsage,
)
from hedwig.core.ports.plugins import (
    Plugin,
    PluginContext,
    PluginLoader,
    PluginManifest,
    PluginRecord,
    PluginStatus,
)
from hedwig.core.ports.registry import (
    Health,
    HealthReporting,
    HealthStatus,
    Lifecycle,
    ServiceInfo,
    ServiceRegistry,
    ServiceStatus,
)
from hedwig.core.ports.scheduler import (
    Priority,
    RunStatus,
    TaskContext,
    TaskHandler,
    TaskResult,
    TaskRun,
    TaskScheduler,
    TaskSpec,
    TaskStatus,
    Trigger,
    TriggerKind,
)
from hedwig.core.ports.sessions import (
    Conversation,
    MessageRole,
    TurnRecord,
    WindowMessage,
    WorkingSetRecord,
)
from hedwig.core.ports.state import (
    Mutator,
    NamespaceInfo,
    StateDocument,
    StateManager,
    StateRevision,
    StateSnapshot,
    StateValue,
)
from hedwig.core.ports.storage import BlobRef, FileStorage, StorageStats

__all__ = [
    "DIMENSIONS",
    "NEUTRAL",
    "Appraisal",
    "AppraisalDimension",
    "BehaviourParameters",
    "BlobRef",
    "Clock",
    "ConfigChange",
    "ConfigEntry",
    "ConfigListener",
    "ConfigManager",
    "ConfigSource",
    "ContextItem",
    "Conversation",
    "Delivery",
    "Dimension",
    "EmotionReader",
    "EmotionSnapshot",
    "EmotionState",
    "Event",
    "EventBus",
    "EventHandler",
    "FileStorage",
    "FinishReason",
    "GenerationRequest",
    "GenerationResult",
    "Guard",
    "Health",
    "HealthReporting",
    "HealthStatus",
    "Intent",
    "LLMProvider",
    "Lifecycle",
    "Message",
    "MessageRole",
    "MindReader",
    "ModelInfo",
    "ModelTier",
    "Mutator",
    "NamespaceInfo",
    "Plan",
    "Planner",
    "Plugin",
    "PluginContext",
    "PluginLoader",
    "PluginManifest",
    "PluginRecord",
    "PluginStatus",
    "Priority",
    "ProviderHealth",
    "RecalledContext",
    "Recaller",
    "RequestPriority",
    "Responder",
    "ResponseContext",
    "Role",
    "RunStatus",
    "SafetyVerdict",
    "ServiceInfo",
    "ServiceRegistry",
    "ServiceStatus",
    "StateDocument",
    "StateManager",
    "StateRevision",
    "StateSnapshot",
    "StateValue",
    "StorageStats",
    "StreamChunk",
    "Subscription",
    "TaskContext",
    "TaskHandler",
    "TaskResult",
    "TaskRun",
    "TaskScheduler",
    "TaskSpec",
    "TaskStatus",
    "TokenUsage",
    "ToolOutcome",
    "ToolRequest",
    "ToolRunner",
    "Trigger",
    "TriggerKind",
    "TrustTier",
    "TurnAnnouncer",
    "TurnPolicy",
    "TurnRecord",
    "TurnSummary",
    "WindowMessage",
    "WorkingSetRecord",
]
